### ISSUE TITLE
shape embedding initialize 

### ISSUE THREAD

**Issue by rockyzhengwu** [iesl/dilated-cnn-ner#2]
```
            if self.use_shape:
                shape_embeddings_shape = (self.shape_domain_size - 1, self.shape_size)
                w_s = tf_utils.initialize_embeddings(shape_embeddings_shape, name="w_s")
                shape_embeddings = tf.nn.embedding_lookup(w_s, input_x2)
                input_list.append(shape_embeddings)
                input_size += self.shape_size
```
in bilstm.py 123 line , w_s will be initialize every  forward ,  there is something wrong ?  

Ithink should init w_s in __init__ function 
```
  if self.use_shape:
        shape_embeddings_shape = (self.shape_domain_size - 1, self.shape_size)
        self.w_s = tf_utils.initialize_embeddings(shape_embeddings_shape, name="w_s")
```
and in forward function write like this:
```
 if self.use_shape:
        # shape_embeddings_shape = (self.shape_domain_size - 1, self.shape_size)
        # w_s = tf_utils.initialize_embeddings(shape_embeddings_shape, name="w_s")
        shape_embeddings = tf.nn.embedding_lookup(self.w_s, input_x2)
        input_list.append(shape_embeddings)
        input_size += self.shape_size
```

**Comment by strubell** [comment]
Thanks for pointing this out! I'll try to take a look later this week.

**Comment by strubell** [comment]
I just took a quick look, and this shouldn't be a problem since `tf_utils.initialize_embeddings` uses `tf.get_variable` (not `tf.Variable`), which would throw an error if the code tried to initialize the same variable twice. If you can provide a small example which shows that this is being re-initialized then I can take a look, otherwise I am going to close this issue.

**Comment by rockyzhengwu** [comment]
thank you !!! , i see
