### ISSUE TITLE
Make pip-installable & add API for easy cross-proj use

### ISSUE THREAD

**Issue by strubell** [iesl/dilated-cnn-ner#5]
@eddotman I think there's an email about this but let's move the conversation here -- I think the best way for us to integrate this tagger with the main predsynth code is for me to (1) add a nice API which takes tokens and labels them (we should sync on the best way to do this, but I know @MSheshera has already coded something up that does this) and (2) make this project pip-installable so that you can just install it and then use it as a library. How does this solution sound?

**Comment by MSheshera** [comment]
I *think* what I did was to stick with your design, I just threw in a way (I mapped the paper dois to an integer in pre-processing and it was part of each batch of sequences) to keep track of the paper a token was coming from and to write it out. This was a hack and I was very uncomfortable doing it. This was the pull request I had submitted to simple-cnn-ner. 

But then I added some more changes to make everything work on the giant million material science papers dataset (these changes are still on my machine and blake and nowhere else) because I remember there was some point in simple-cnn-ner where you loaded some split of the dataset into memory completely. (but I may be wrong) 

I'll submit these changes also in my new pull request and you can see if any of it is helpful. I'll try to do this as soon as I can. Probably between 20th and 23rd.

**Comment by strubell** [comment]
Great, thanks!

**Comment by eddotman** [comment]
(1) Agreed on the API. Currently, we do this ( https://github.com/olivettigroup/synthesis-database/blob/master/synthesisdatabase/classifiers/token_classifier.py#L195-L205 ) where we pass in a list of words and receive back an equal-length list of labels (per word).

(2) Also agreed on the pip-installable strategy. e.g. that's exactly what we did internally for document retrieval ( https://github.com/olivettigroup/article-downloader ) <-- that gets pip-installed and imported in the `synthesis-database` repo.

**Comment by eddotman** [comment]
@strubell @MSheshera lemme know if there's anything I can help with for this btw - I'm happy to make some changes and make a pull request if it seems useful to do things that way!
